name       : mp3gain
version    : 1.5.2
release    : 1
source     :
    - http://nbtelecom.dl.sourceforge.net/project/mp3gain/mp3gain/1.5.2/mp3gain-1_5_2_r2-src.zip : 3378d32c8333c14f57622802f6a92b725f36ee45a6b181657b595b1b5d64260f
license    : LGPL-2.1
component  : multimedia.audio
summary    : Adjusts mp3 files to play at the same volume
description: |
    MP3Gain analyzes and adjusts mp3 files to play at the same volume.
extract    : no
builddeps  :
    - unzip
setup      : |
    mkdir mp3gain
    cd mp3gain
    unzip $sources/mp3gain-1_5_2_r2-src.zip
build      : |
    %make
install    : |
    install -Dm755 $workdir/mp3gain %installroot%/usr/bin/mp3gain
