name       : mp3gain
version    : 1.6.2
release    : 3
source     :
    - https://nchc.dl.sourceforge.net/project/mp3gain/mp3gain/1.6.2/mp3gain-1_6_2-src.zip : 5cc04732ef32850d5878b28fbd8b85798d979a025990654aceeaa379bcc9596d
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : Adjusts mp3 files to play at the same volume
description: |
    MP3Gain analyzes and adjusts mp3 files to play at the same volume.
builddeps  :
    - pkgconfig(libmpg123)
build      : |
    %make
install    : |
    install -Dm00755 $workdir/mp3gain %installroot%/usr/bin/mp3gain
